### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by dwellons** [dwellons/DonationLog#7]
Hello @pawaitemadisoncollege , I believe I have checkpoint 2 ready for review!

**Comment by pawaitemadisoncollege** [comment]
Hi @dwellons! Following are my notes from a review for CP 2:

**Database designed and created** Clearly you have this created because you've been doing your weekly work in your indie project! 

- [ ] can you share the ERD for your database so that I can review and provide feedback? If you don't already have a preferred way to create this, you can generate it from the database view in IntelliJ (right click and use diagrams). 

**at least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate**

**DAO is fully unit tested**

- [ ] See https://github.com/dwellons/DonationLog/issues/4.

- [ ] In addition, now you can implement the generic dao to eliminate the duplication in the entity-specific daos.  The unit tests will stay, just convert them over to use the GenericDao and then remove the entity-specify daos.  Let me know if that doesn't make sense or you have other questions. 

**Log4J is implemented (no System.out.printlns)**

- [ ] I mentioned this in my code review feedback, but including it here too: https://github.com/search?q=repo%3Adwellons%2FDonationLog%20println&type=code

**Other**

Project plan needs some updating. Now that you are further into the class and development. Can you outline what you need to do over the remaining 8 weeks?

**Comment by dwellons** [comment]
@pawaitemadisoncollege Hello! I just wanted to send a message and say that I have seen this and the other issues that are open and am just waiting until after I get back next week to sit down and make all the corrections to the things! I have some questions too I want to ask about before I start working on some things

**Comment by dwellons** [comment]
@pawaitemadisoncollege I have a little extra time today and started working on your suggestions! Here is my ERD, I've thought I've had a one to many relationship but after seeing this I don't think that I am, so I am going to have to look at that too.
<img width="1773" alt="Screenshot 2024-03-10 at 12 57 40 PM" src="https://github.com/dwellons/DonationLog/assets/143457620/0115e1f6-b6ed-4fd9-bbc3-c02db8e78be4">

**Comment by pawaitemadisoncollege** [comment]
Hi @dwellons -I have a couple ideas to normalize this.  Move donor to its own table.  A donor can have 0 to many donations.  You could also put donation_type on its own table - sort of a look up table. This could also feed the choices in a select box in UI when entering a donation... Does that make sense?
